version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=recipe_db

  recipe-api:
    build: .
    container_name: recipe-api
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MONGODB_URI=mongodb+srv://elieissa:1234@cluster0.wgnomye.mongodb.net/recipe_db?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=6c0f0014f71deeacf37fa86a8d4eb27d
      - JWT_EXPIRATION=86400

volumes:
  mongodb_data: